; config.ini
[GV]
KEY = /New_Volume/number_theory/table_processing/utils/gvkey.json

[PATH]
DETECT_IMAGE_SAVE_PATH = ../data/output/ingram_abby/columns/cv/images_new
OCR_PATH = ../data/output/ingram_abby/ocr
IMAGE_FOLDER = ../data/output/ingram_abby/tables
SAVE_COORDS_DETECT_COORDS = /New_Volume/master_table_extraction/data/output/ingram_abby/columns/cv/jsons
HEADER_COORDS = /New_Volume/master_table_extraction/data/test/ingram_test_abby/headers/final_json
HEADER_STRIP = ../data/output/ingram_abby/headers/final_header.json


FINAL_IMAGE_SAVE_PATH = /New_Volume/master_table_extraction/data/test/ingram_test_abby/columns/image
FINAL_COORDS_SAVE_PATH = /New_Volume/master_table_extraction/data/test/ingram_test_abby/headers/json
; SAVE_COLS_DETEC_COORDS_TO = /New_Volume/number_theory/table_processing/_data/res/col_out_dec_6/jsons

[SERVICE]
MODEL_IMAGE_PATH = Model/image-model/
MACHINE_IP = http://192.168.164.102
MODEL_PORT = 8016
VERIFICATION_PORT = 8015
VERIFICATION_URL = http://192.168.164.102:8015
MODEL_THREAD_POOL = 10
MODEL_PROXY_BASE = 127.0.0.1
MODEL_SOCKET_HOST = 0.0.0.0
LOG_IMAGE = no
MODEL_PATH = Model
