[DEFAULT]

out_dir = /New_Volume/number_theory/table_processing/data/output/apollo/row/tatr
detection_device = cpu
structure_device = cpu
; detection_config_path = None
; detection_model_path = None
words_dir = 
structure_config_path = ./inference/configs/tatr_structure_config.json
structure_model_path = ./models/finetuned/tatr_best_model_ap_0.68_35.pth
mode = recognize    
objects = True
crops = True
html = False
csv = False
verbose = False
visualize = False
crop_padding = 10
