[MODE]
; BATCH = FALSE
DUMP = TRUE

; [MODULE]
; ROW = FALSE
; COLUMN = FALSE
; HEADER = FALSE
; TABLE = FALSE

[DATASET]
NAME = test_march_12

[OCR]
TESSERACT = FALSE
ABBY = FALSE
GV = FALSE
OTHER = TRUE

[PATH]
DOC_PATH = ./data/input/ingram_deskewed
DUMP_PATH = ./data/output
GV_CREDENTIALS = ./utils/gvkey.json

; required if using custom ocr input
OCR_PATH = ./data/input/ingram_deskewed_ocr